### ISSUE TITLE
Seeded maze

### ISSUE THREAD

**Issue by Onheiron** [bestguy/generate-maze#2]
Would be nice to have a seed option to generate the same maze when given the same seed.

**Comment by bestguy** [comment]
Great idea, would need a new random number generator, but should be doable.  I'll take a look soon hopefully

**Comment by Quinten** [comment]
I would also love this feature. What about using https://github.com/davidbau/seedrandom as random number generator? Would that work?

**Comment by bestguy** [comment]
Thanks for the reminder.  Will take a look this week, or pr is welcome as well.

**Comment by bestguy** [comment]
Hi @Onheiron @Quinten ,

Sorry for long delay but added seed as a 4th parameter in #3 
Also updated the library and build quite a bit, published as generate-maze@1.0.2 if would like to try out.

Sample usage is in Readme or see example here: https://svelte.dev/repl/7eb34401ec0c42d3bb47d2cdbc58f926?version=3.38.2

**Comment by bestguy** [comment]
Please close if this works out for you

**Comment by Quinten** [comment]
Looks great! Seems to work for me.

So the seed needs to be an integer? Strings and floats won't work, i noticed in the example, but numbers like `0xffffffff` do work. That's ok for me.

Thanks for the effort!

I can't close the issue (no permission). @Onheiron will have to do that.
