### ISSUE TITLE
Cannot generate maze

### ISSUE THREAD

**Issue by norisurgit** [bestguy/generate-maze#4]
Here is the code I pasted and ran:
`const generator = require('generate-maze');`
`const maze = generator(4);`

I'm using:

- Node v15.14.0
- Windows 10 64bit

![image](https://user-images.githubusercontent.com/12083695/126812716-0231e8a1-318d-44bd-b92d-53caf62bbc5c.png)

**Comment by bestguy** [comment]
Hi thanks, looks like the compilation or config is not right outside the browser, will take a look

**Comment by bestguy** [comment]
Hi @norisurgit , this should be fixed in `generate-maze@1.1.0`, thanks for the heads up 👍.

**Comment by bestguy** [comment]
This supports `require`, or `import` if your node app is a module.   Please comment or reopen if still seeing issues.
