### ISSUE TITLE
Solver

### ISSUE THREAD

**Issue by netgfx** [bestguy/generate-maze#6]
Hello, do you happen to have a script that solves the maze? Produces the path between the left most block and the right most bottom one?

**Comment by bestguy** [comment]
Hi @netgfx , no I don't.  Some ideas might be here: https://en.wikipedia.org/wiki/Maze-solving_algorithm

**Comment by netgfx** [comment]
In case someone is wondering, I've managed to solve this type of mazes with `pathfinding.js` you can check this issue here: https://github.com/qiao/PathFinding.js/issues/203 for more information.
thanks for the wonderful library @bestguy !

**Comment by bestguy** [comment]
Very cool thanks @netgfx !
